In [ ]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from nltk.tokenize import word_tokenize
from numpy.linalg import norm
import pandas as pd
import numpy as np
import requests
import re
import multiprocessing
import plotly.graph_objects as go
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

## JD model

In [5]:
jd_data = pd.read_csv('data/jobs_data/JobsDataset.csv') 
jd_data.drop(['ID','Query'], axis=1, inplace=True)
jd_data['data'] = jd_data[['Job Title','Description']].apply(lambda x: ' '.join(x.dropna().astype(str)), axis=1)
tagged_data = [TaggedDocument(words = word_tokenize(_d.lower()), tags = [str(i)]) for i, _d in enumerate(jd_data['data'])]

In [6]:
epochs_list = [80, 100, 150]

for epochs in epochs_list:
    model = Doc2Vec(vector_size = 50,
    min_count = 3,
    epochs = epochs,
    alpha = 0.001,
    workers = 16
    )
    model.build_vocab(tagged_data)
    model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)
    
    # Save or use the trained model here based on your needs
    model.save(f'doc2vec_model_epochs_{epochs}.model')

In [24]:


jd_data['data'] = jd_data[['Job Title','Description']].apply(lambda x: ' '.join(x.dropna().astype(str)), axis=1)
tagged_data = [TaggedDocument(words = word_tokenize(_d.lower()), tags = [str(i)]) for i, _d in enumerate(jd_data['data'])]
model = Doc2Vec(vector_size = 50,
min_count = 3,
epochs = 40,
alpha = 0.001,
workers = 4
)
model.build_vocab(tagged_data)

In [15]:
jd_data

,Job Title,Description,data
0,Junior Data Scientist Apprenticeship,Job Description As a Junior Data Scientist at ...,Junior Data Scientist Apprenticeship Job Descr...
1,"HBO Data Scientist, Content Science",OVERALL SUMMARY As a Data Scientist on the Dat...,"HBO Data Scientist, Content Science OVERALL SU..."
2,Junior Data Scientist,The Team: The Data science team is a newly for...,Junior Data Scientist The Team: The Data scie...
3,Jr Data Scientist,We now have a need for junior Data Scientist(s...,Jr Data Scientist We now have a need for junio...
4,"Data Scientist, Premium Content",Do you want to help guide the core business of...,"Data Scientist, Premium Content Do you want t..."
...,...,...,...
9993,Learning Architect,The opportunity Our customers understand that ...,Learning Architect The opportunity Our custome...
9994,Systems Architect,The NASA Ames Research Center has the requirem...,Systems Architect The NASA Ames Research Cente...
9995,Hardware Architect,What You'll Do Distinguished Engineer with pro...,Hardware Architect What You'll Do Distinguish...
9996,"Software Development Engineer, Full Stack – E...","Software Development Engineer, Full Stack – En...","Software Development Engineer, Full Stack – E..."
9997,Architect,"Architect San Francisco, CA Leading provider o...","Architect Architect San Francisco, CA Leading ..."

In [25]:
# Vocabulary building
model.build_vocab(tagged_data)
# Get the vocabulary keys
keys = model.wv.key_to_index.keys()
# Print the length of the vocabulary keys
print(len(keys))

27351

In [23]:
num_workers = multiprocessing.cpu_count()  # Use all available cores (4 in your case)
num_workers

16

In [26]:
# Train the model
for epoch in range(model.epochs):
    print(f"Training epoch {epoch+1}/{model.epochs}")
    model.train(tagged_data, 
                total_examples=model.corpus_count, 
                epochs=model.epochs)

model.save('cv_job_maching.model')
print("Model saved")

Training epoch 1/40
Training epoch 2/40
Training epoch 3/40
Training epoch 4/40
Training epoch 5/40
Training epoch 6/40
Training epoch 7/40
Training epoch 8/40
Training epoch 9/40
Training epoch 10/40
Training epoch 11/40
Training epoch 12/40
Training epoch 13/40
Training epoch 14/40
Training epoch 15/40
Training epoch 16/40
Training epoch 17/40
Training epoch 18/40
Training epoch 19/40
Training epoch 20/40
Training epoch 21/40
Training epoch 22/40
Training epoch 23/40
Training epoch 24/40
Training epoch 25/40
Training epoch 26/40
Training epoch 27/40
Training epoch 28/40
Training epoch 29/40
Training epoch 30/40
Training epoch 31/40
Training epoch 32/40
Training epoch 33/40
Training epoch 34/40
Training epoch 35/40
Training epoch 36/40
Training epoch 37/40
Training epoch 38/40
Training epoch 39/40
Training epoch 40/40
Model saved

In [28]:
def preprocess_text(text):
    # Convert the text to lowercase
    text = text.lower()
    
    # Remove punctuation from the text
    text = re.sub('[^a-z]', ' ', text)
    
    # Remove numerical values from the text
    text = re.sub(r'\d+', '', text)
    
    # Remove extra whitespaces
    text = ' '.join(text.split())
    
    return 
def remove_accents(input_string):
    accents = {'é': 'e', 'è': 'e', 'ê': 'e', 'ë': 'e', 'É': 'E', 'È': 'E', 'Ê': 'E', 'Ë': 'E',
        'à': 'a',
        'â': 'a',
        'ç': 'c',
        'î': 'i',
        'ï': 'i',
        'ô': 'o',
        'ù': 'u',
        'û': 'u'
        # Add more replacements as needed
    }
def remove_initial_newlines(text):
    sentence_found = False
    new_text = ''

    for char in text:
        if not sentence_found:
            if char == '\n':
                continue
            else:
                sentence_found = True
                new_text += char
        else:
            new_text += char

    return new_text
def remove_first_lines(text):
    first_lines_removed= remove_initial_newlines(text)
    return '\n'.join(first_lines_removed.split('\n', 1)[1:])

In [ ]:
import sys
sys.path.append('..')
from tika import parser
def read_file(file,path):
  """Reads a file and returns the content."""
  try:
    parsed_pdf = parser.from_file(path+'/'+file)
    non_accent = remove_accents(parsed_pdf['content'].lower())
    return remove_first_lines(non_accent) 
  except Exception as e:
    # Catch any other exceptions and log error message
    logging.error("Error while reading the file: " + str(e))
    return None

In [3]:
jd_data = pd.read_csv('data/jobs_data/JobsDataset.csv')

In [43]:
scores = pd.read_csv('data/scores.csv') 
model_80 = Doc2Vec.load('doc2vec_model_epochs_80.model')
model_100 = Doc2Vec.load('doc2vec_model_epochs_100.model')
model_150 = Doc2Vec.load('doc2vec_model_epochs_150.model')

In [5]:
scores = pd.read_csv('data/scores.csv')

In [52]:
import pandas as pd

data = [
    ("model80", "react", "CV_Amine_Gafsi.pdf", 39.359495, 5.0),
    ("model100", "react", "CV_Amine_Gafsi.pdf", 32.219495, 6.0),
    ("model150", "react", "CV_Amine_Gafsi.pdf", 28.419495, 6.0),
    ("model80", "laravel", "CV_Amine_Gafsi.pdf", 34.438757, 5.0),
    ("model100", "laravel", "CV_Amine_Gafsi.pdf", 30.053757, 6.0),
    ("model150", "laravel", "CV_Amine_Gafsi.pdf", 23.308757, 7.0),
    ("model80", "react", "laravel.pdf", 49.989495, 4.0),
    ("model100", "react", "laravel.pdf", 49.459495, 4.0),
    ("model150", "react", "laravel.pdf", 47.399495, 4.0),
    ("model80", "laravel", "laravel.pdf", 52.281852, 3.0),
    ("model100", "laravel", "laravel.pdf", 48.561852, 4.0),
    ("model150", "laravel", "laravel.pdf", 48.486852, 4.0),
    ("model80", "react", "rayen.pdf", 27.104356, 7.0),
    ("model100", "react", "rayen.pdf", 25.744356, 7.0),
    ("model150", "react", "rayen.pdf", 27.759356, 7.0),
    ("model80", "laravel", "rayen.pdf", 30.883287, 7.0),
    ("model100", "laravel", "rayen.pdf", 28.218287, 7.0),
    ("model150", "laravel", "rayen.pdf", 34.018287, 5.0),
    ("model80", "react", "react3.pdf", 50.766428, 3.0),
    ("model100", "react", "react3.pdf", 52.576428, 2.0),
    ("model150", "react", "react3.pdf", 52.596428, 2.0),
    ("model80", "laravel", "react3.pdf", 49.413287, 4.0),
    ("model100", "laravel", "react3.pdf", 48.603287, 3.0),
    ("model150", "laravel", "react3.pdf", 50.028287, 3.0),
    ("model80", "react", "react_native.pdf", 57.985000, 1.0),
    ("model100", "react", "react_native.pdf", 55.725000, 1.0),
    ("model150", "react", "react_native.pdf", 53.400000, 1.0),
    ("model80", "laravel", "react_native.pdf", 53.378287, 2.0),
    ("model100", "laravel", "react_native.pdf", 52.938287, 2.0),
    ("model150", "laravel", "react_native.pdf", 54.128287, 1.0),
    ("model80", "react", "react_native2.pdf", 33.875000, 6.0),
    ("model100", "react", "react_native2.pdf", 32.980000, 5.0),
    ("model150", "react", "react_native2.pdf", 33.950000, 5.0),
    ("model80", "laravel", "react_native2.pdf", 32.195000, 6.0),
    ("model100", "laravel", "react_native2.pdf", 31.885000, 5.0),
    ("model150", "laravel", "react_native2.pdf", 32.870000, 6.0),
    ("model80", "react", "react_native4.pdf", 51.510000, 2.0),
    ("model100", "react", "react_native4.pdf", 50.410000, 3.0),
    ("model150", "react", "react_native4.pdf", 49.690000, 3.0),
    ("model80", "laravel", "react_native4.pdf", 56.816852, 1.0),
    ("model100", "laravel", "react_native4.pdf", 55.131852, 1.0),
    ("model150", "laravel", "react_native4.pdf", 53.146852, 2.0),
    ("model80", "react", "scrum_master.pdf", 13.745000, 8.0),
    ("model100", "react", "scrum_master.pdf", 9.945000, 8.0),
    ("model150", "react", "scrum_master.pdf", 14.270000, 8.0),
    ("model80", "laravel", "scrum_master.pdf", 24.010000, 8.0),
    ("model100", "laravel", "scrum_master.pdf", 17.885000, 8.0),
    ("model150", "laravel", "scrum_master.pdf", 21.940000, 8.0)
]

df_pred = pd.DataFrame(data, columns=["model", "type", "name", "similarity", "pred_ranking"])
df_pred

       model     type                name  similarity  pred_ranking
0    model80    react  CV_Amine_Gafsi.pdf   39.359495           5.0
1   model100    react  CV_Amine_Gafsi.pdf   32.219495           6.0
2   model150    react  CV_Amine_Gafsi.pdf   28.419495           6.0
3    model80  laravel  CV_Amine_Gafsi.pdf   34.438757           5.0
4   model100  laravel  CV_Amine_Gafsi.pdf   30.053757           6.0
5   model150  laravel  CV_Amine_Gafsi.pdf   23.308757           7.0
6    model80    react         laravel.pdf   49.989495           4.0
7   model100    react         laravel.pdf   49.459495           4.0
8   model150    react         laravel.pdf   47.399495           4.0
9    model80  laravel         laravel.pdf   52.281852           3.0
10  model100  laravel         laravel.pdf   48.561852           4.0
11  model150  laravel         laravel.pdf   48.486852           4.0
12   model80    react           rayen.pdf   27.104356           7.0
13  model100    react           rayen.pdf   25.744356           7.0
14  model150    react           rayen.pdf   27.759356           7.0
15   model80  laravel           rayen.pdf   30.883287           7.0
16  model100  laravel           rayen.pdf   28.218287           7.0
17  model150  laravel           rayen.pdf   34.018287           5.0
18   model80    react          react3.pdf   50.766428           3.0
19  model100    react          react3.pdf   52.576428           2.0
20  model150    react          react3.pdf   52.596428           2.0
21   model80  laravel          react3.pdf   49.413287           4.0
22  model100  laravel          react3.pdf   48.603287           3.0
23  model150  laravel          react3.pdf   50.028287           3.0
24   model80    react    react_native.pdf   57.985000           1.0
25  model100    react    react_native.pdf   55.725000           1.0
26  model150    react    react_native.pdf   53.400000           1.0
27   model80  laravel    react_native.pdf   53.378287           2.0
28  model100  laravel    react_native.pdf   52.938287           2.0
29  model150  laravel    react_native.pdf   54.128287           1.0
30   model80    react   react_native2.pdf   33.875000           6.0
31  model100    react   react_native2.pdf   32.980000           5.0
32  model150    react   react_native2.pdf   33.950000           5.0
33   model80  laravel   react_native2.pdf   32.195000           6.0
34  model100  laravel   react_native2.pdf   31.885000           5.0
35  model150  laravel   react_native2.pdf   32.870000           6.0
36   model80    react   react_native4.pdf   51.510000           2.0
37  model100    react   react_native4.pdf   50.410000           3.0
38  model150    react   react_native4.pdf   49.690000           3.0
39   model80  laravel   react_native4.pdf   56.816852           1.0
40  model100  laravel   react_native4.pdf   55.131852           1.0
41  model150  laravel   react_native4.pdf   53.146852           2.0
42   model80    react    scrum_master.pdf   13.745000           8.0
43  model100    react    scrum_master.pdf    9.945000           8.0
44  model150    react    scrum_master.pdf   14.270000           8.0
45   model80  laravel    scrum_master.pdf   24.010000           8.0
46  model100  laravel    scrum_master.pdf   17.885000           8.0
47  model150  laravel    scrum_master.pdf   21.940000           8.0

In [2]:
pred_results = pd.read_csv("perdicted_results.csv")

In [3]:
pred_results

    Unnamed: 0     model     type                name  similarity  ranking
0            0   model80    react  CV_Amine_Gafsi.pdf   39.689495      5.0
1            1  model100    react  CV_Amine_Gafsi.pdf   32.449495      6.0
2            2  model150    react  CV_Amine_Gafsi.pdf   28.574495      6.0
3            3   model40    react  CV_Amine_Gafsi.pdf   50.544495      6.0
4            4   model80  laravel  CV_Amine_Gafsi.pdf   34.563757      5.0
..         ...       ...      ...                 ...         ...      ...
59          59   model40    react    scrum_master.pdf   31.185000      8.0
60          60   model80  laravel    scrum_master.pdf   24.130000      8.0
61          61  model100  laravel    scrum_master.pdf   17.875000      8.0
62          62  model150  laravel    scrum_master.pdf   21.960000      8.0
63          63   model40  laravel    scrum_master.pdf   31.240000      8.0

[64 rows x 6 columns]

In [6]:
scores['name']

0     CV_Amine_Gafsi
1            laravel
2              rayen
3       react_native
4      react_native2
5             react3
6      react_native4
7       scrum_master
8     CV_Amine_Gafsi
9            laravel
10             rayen
11      react_native
12     react_native2
13            react3
14     react_native4
15      scrum_master
Name: name, dtype: object

In [7]:
scores['name'] = scores['name']+'.pdf'

In [8]:
merged_df = pd.merge(pred_results, scores, on=["name", "type"])

In [9]:
merged_df

,Unnamed: 0,model,type,name,similarity,ranking_x,ranking_y
0,0,model80,react,CV_Amine_Gafsi.pdf,39.689495,5.0,7
1,1,model100,react,CV_Amine_Gafsi.pdf,32.449495,6.0,7
2,2,model150,react,CV_Amine_Gafsi.pdf,28.574495,6.0,7
3,3,model40,react,CV_Amine_Gafsi.pdf,50.544495,6.0,7
4,4,model80,laravel,CV_Amine_Gafsi.pdf,34.563757,5.0,8
...,...,...,...,...,...,...,...
59,59,model40,react,scrum_master.pdf,31.185000,8.0,8
60,60,model80,laravel,scrum_master.pdf,24.130000,8.0,7
61,61,model100,laravel,scrum_master.pdf,17.875000,8.0,7
62,62,model150,laravel,scrum_master.pdf,21.960000,8.0,7
63,63,model40,laravel,scrum_master.pdf,31.240000,8.0,7

### Jd model evalutions

In [30]:
merged_df['ranking_x'] = merged_df['ranking_x'].astype('int64')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64 entries, 32 to 63
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  64 non-null     int64
 1   model       64 non-null     object
 2   type        64 non-null     object
 3   name        64 non-null     object
 4   similarity  64 non-null     float64
 5   ranking_x   64 non-null     int64
 6   ranking_y   64 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 4.0+ KB

In [54]:
merged_df.sort_values(by='ranking_x',ascending=True,inplace=True)
models=merged_df['model'].unique().tolist()

['model80', 'model100', 'model150', 'model40']

In [79]:
test_df=merged_df[['ranking_x','ranking_y']] <= 4
deno = test_df['ranking_x'].sum()
test_df

    ranking_x  ranking_y
32       True       True
33       True       True
34       True       True
35       True       True
52       True      False
..        ...        ...
61      False      False
62      False      False
60      False      False
59      False      False
63      False      False

[64 rows x 2 columns]

In [81]:
deno

32

In [80]:
test_df['ranking_x'].value_counts()

True     32
False    32
Name: ranking_x, dtype: int64

In [39]:
def precision_at_k(df: pd.DataFrame, k: int=3, y_test: str='ranking_y', y_pred: str='ranking_x') -> float:
    if k <= 0:
        raise ValueError('Value of k should be greater than 1, read in as: {}'.format(k))
    # check y_test & y_pred columns are in df
    if y_test not in df.columns:
        raise ValueError('Input dataframe does not have a column named: {}'.format(y_test))
    if y_pred not in df.columns:
        raise ValueError('Input dataframe does not have a column named: {}'.format(y_pred))
    dfK = df.head(k)
    denominator = dfK[y_pred].sum()
    numerator = dfK[dfK[y_pred] & dfK[y_test]].shape[0]
    if denominator > 0:
        return numerator/denominator
    else:
        return None
precision_at_k(df,3,'ranking_y','ranking_x')

1.0

In [86]:
threshold = 3
for model in models : 
    model_df = merged_df[merged_df['model']==model]
    model_df=model_df[['ranking_x','ranking_y']] <= threshold
    precision = precision_at_k(model_df,3,'ranking_y','ranking_x')
    print(f'percision for the {model} is : {precision}')

percision for the model80 is : 0.6666666666666666
percision for the model100 is : 0.6666666666666666
percision for the model150 is : 1.0
percision for the model40 is : 1.0

In [68]:
from scipy.stats import kendalltau

In [74]:
models = ["model40","model80", "model100", "model150"]
kendall_tau_scores = {}

for model in models:
    model_data = merged_df[merged_df["model"] == model]
    kendall_tau, _ = kendalltau(model_data["ranking_x"], model_data["ranking_y"])
    kendall_tau_scores[model] = kendall_tau

In [76]:
kendall_tau_scores

{'model40': 0.4821428571428571,
 'model80': 0.3839285714285714,
 'model100': 0.49107142857142855,
 'model150': 0.5535714285714285}

### Resume model

In [87]:
resumes = pd.read_csv('data/raw_data/resumes.csv')

In [125]:
import re
def cleanResume(resumeText):
    resumeText = re.sub('http\S+\s*', ' ', resumeText)  # remove URLs
    resumeText = re.sub('RT|cc', ' ', resumeText)  # remove RT and cc
    resumeText = re.sub('#\S+', '', resumeText)  # remove hashtags
    resumeText = re.sub('@\S+', '  ', resumeText)  # remove mentions
    resumeText = re.sub('[%s]' % re.escape("""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""), ' ', resumeText)  # remove punctuations
    resumeText = re.sub(r'[^\x00-\x7f]',r' ', resumeText) 
    resumeText = re.sub('\s+', ' ', resumeText)  # remove extra whitespace
    return resumeText
    
resumes['cleaned_resume'] = resumes.Resume.apply(lambda x: cleanResume(x))

In [ ]:
nltk.download('stopwords')

In [130]:
nltk.download('wordnet')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\rayen\AppData\Roaming\nltk_data...
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\rayen\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [135]:
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
def preprocess_resume_text(text, tag):
    text = cleanResume(text)
    ''' 
stemming Example:

Original: jumping, jumps, jumped
Stemmed: jump
lemmetizing Example:

Original: jumping, jumps, jumped
Lemmatized: jump
'''
    filtered_text = ' '.join([word for word in word_tokenize(text) if word.lower() not in stop_words])
    tokens = word_tokenize(filtered_text)
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in tokens]
    stemmed_tokens = [stemmer.stem(token) for token in lemmatized_tokens]
    return TaggedDocument(words=stemmed_tokens, tags=[str(tag)])

#tagged_data_res_2 = [preprocess_resume_text(_d, i) for i, _d in enumerate(resumes['cleaned_resume'])]

In [134]:
epochs_list = [80, 100, 150]

for epochs in epochs_list:
    model = Doc2Vec(vector_size = 50,
    min_count = 4,
    epochs = epochs,
    alpha = 0.001,
    workers = 16
    )
    model.build_vocab(tagged_data_res_2)
    model.train(tagged_data_res_2, total_examples=model.corpus_count, epochs=model.epochs)
    
    # Save or use the trained model here based on your needs
    model.save(f'resumes_model_epochs_{epochs}.model')

In [140]:
!pip list

Package            Version
------------------ ---------
asttokens          2.2.1
backcall           0.2.0
beautifulsoup4     4.12.2
blis               0.7.10
catalogue          2.0.9
certifi            2023.7.22
charset-normalizer 3.2.0
click              8.1.6
colorama           0.4.6
confection         0.1.1
cymem              2.0.7
decorator          5.1.1
deep-translator    1.11.4
en-core-web-lg     3.5.0
en-core-web-sm     3.5.0
executing          1.2.0
filelock           3.12.2
fsspec             2023.6.0
fuzzywuzzy         0.18.0
gensim             4.3.1
huggingface-hub    0.16.4
idna               3.4
ipython            8.14.0
jedi               0.19.0
jellyfish          1.0.0
Jinja2             3.1.2
joblib             1.3.2
langcodes          3.3.0
langdetect         1.0.9
Levenshtein        0.21.1
MarkupSafe         2.1.3
matplotlib-inline  0.1.6
mpmath             1.3.0
murmurhash         1.0.9
networkx           3.1
nltk               3.8.1
numpy              1.25.2
packaging          23.1
pandas             2.0.3
parso              0.8.3
pathy              0.10.2
pickleshare        0.7.5
pip                23.2.1
preshed            3.0.8
prompt-toolkit     3.0.39
pure-eval          0.2.2
pydantic           1.10.12
Pygments           2.16.1
python-dateutil    2.8.2
python-Levenshtein 0.21.1
pytz               2023.3
PyYAML             6.0.1
rapidfuzz          3.2.0
regex              2023.8.8
requests           2.31.0
safetensors        0.3.2
scikit-learn       1.3.0
scipy              1.11.1
setuptools         68.0.0
six                1.16.0
skillNer           1.0.3
smart-open         6.3.0
soupsieve          2.4.1
spacy              3.5.0
spacy-alignments   0.9.0
spacy-legacy       3.0.12
spacy-loggers      1.0.4
spacy-transformers 1.2.5
srsly              2.4.7
stack-data         0.6.2
sympy              1.12
thinc              8.1.12
threadpoolctl      3.2.0
tika               2.6.0
tokenizers         0.13.3
torch              2.0.1
tqdm               4.66.1
traitlets          5.9.0
transformers       4.30.2
typer              0.7.0
typing_extensions  4.7.1
tzdata             2023.3
urllib3            2.0.4
wasabi             1.1.2
wcwidth            0.2.6
wheel              0.38.4

In [143]:
!pip install deep_translator

Collecting deep_translator
  Obtaining dependency information for deep_translator from https://files.pythonhosted.org/packages/38/3f/61a8ef73236dbea83a1a063a8af2f8e1e41a0df64f122233938391d0f175/deep_translator-1.11.4-py3-none-any.whl.metadata
  Using cached deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\rayen\anaconda3\envs\ats_env\lib\site-packages (from deep_translator) (4.12.2)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\rayen\anaconda3\envs\ats_env\lib\site-packages (from deep_translator) (2.31.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\rayen\anaconda3\envs\ats_env\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rayen\anaconda3\envs\ats_env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rayen\anaconda3\envs\ats_env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rayen\anaconda3\envs\ats_env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rayen\anaconda3\envs\ats_env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep_translator) (2023.7.22)
Using cached deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep_translator
Successfully installed deep_translator-1.11.4

In [ ]:
from deep_translator import GoogleTranslator
from langdetect import detect
def detect_lang(resume_text) :
  lang = detect(resume_text)
  if lang == 'fr' :
    final_text=list()
    for i in range(0, len(resume_text), 50000):
        translation = GoogleTranslator(source='auto', target='en').translate(resume_text[i:i+50000], dest='en')
        final_text.append(translation)
    return ' '.join(final_text)
resume_example = pd.read_csv('data/raw_data/CV_Ahmed_Farhat.pdf')
#preprocessed_resume = preprocess_resume_text(resume_example)
detect_lang(resume_example)